steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        gcloud compute ssh agencies --zone=$(gcloud config get-value compute/zone) --command='/bin/sh /home/ihor_boklach_ir_2021/pull.sh'