steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        vmlist=$(gcloud compute instances list --format='value(name)' --filter="labels.${_VM_LABEL_KEY}:${_VM_LABEL_VALUE} AND status:RUNNING") && for vm in $vmlist; do gcloud compute ssh cloudbuild@$vm --zone $(gcloud compute instances list --format='value(zone)' --filter="name='$vm'") --quiet -- 'gsutil cp gs://agencies_lab_buck/script.sh . && source script.sh && gsutil cp gs://agencies_lab_buck/startup1.sh . && sudo chmod +x startup1.sh && sudo sh startup1.sh && sudo rm startup1.sh'; done
    entrypoint: bash